SYMPTOM_COLUMNS = [f"Symptom_{i}" for i in range(1, 18)]
TARGET_COLUMN = "Disease"

MAX_LEN = 17
PAD_TOKEN = "<PAD>"
UNK_TOKEN = "<UNK>"

RANDOM_STATE = 42
TEST_SIZE = 0.15
VAL_SIZE = 0.15

EMBEDDING_DIM = 64
NUM_EPOCHS = 25
BATCH_SIZE = 32
LEARNING_RATE = 1e-3